name: Deploy to Amazon ECS Fargate
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        type: environment
        required: true
  push:
    branches: 
      - 'main'
env:            
  resourceGroup2: ${{ github.run_number }}

jobs:
  Build-Image:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
    - name: Build & Push docker image to Amazon ECR
      id: build-image
      run: |
        # Build & Push image 
        echo ${{ env.resourceGroup2 }}
